### ISSUE TITLE
Out of space exceptions while logging (does not send email)

### ISSUE THREAD

**Issue by kolmanv** [bbfsdev/bbfs#109] opened 2013-04-12 10:05 UTC
This bug have two action items:
1) Fix logging, such that when there is no space left, send email anyway.
2) Catch no disk space in the proper way in testing server.

Full log:
[INFO] 2013-04-10 05:13:33 Module /home/kolmanv/bbfs/lib/testing_server/testing_server.rb:90:in `run_testing_ser
: /home/kolmanv/.bbfs/var/content.data to /home/kolmanv/.bbfs/var/remote_content.data
[ERROR] 2013-04-10 05:13:34 Module /home/kolmanv/bbfs/lib/testing_server/testing_server.rb:120:in`rescue in run
ppened in testing server: Errno::EDQUOT:Disk quota exceeded - /home/kolmanv/.bbfs/var/remote_content.data, resta
Backtrace:
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-sftp-2.1.1/lib/net/sftp/operations/download.rb:339:in `write'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-sftp-2.1.1/lib/net/sftp/operations/download.rb:339:in`on_read'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-sftp-2.1.1/lib/net/sftp/request.rb:87:in `call'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-sftp-2.1.1/lib/net/sftp/request.rb:87:in`respond_to'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-sftp-2.1.1/lib/net/sftp/session.rb:948:in `dispatch_request'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-sftp-2.1.1/lib/net/sftp/session.rb:911:in`when_channel_polled'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-ssh-2.6.6/lib/net/ssh/connection/channel.rb:311:in `call'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-ssh-2.6.6/lib/net/ssh/connection/channel.rb:311:in`process'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:214:in `block in prepro
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:214:in`each'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:214:in `preprocess'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:197:in`process'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:161:in `block in loop'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:161:in`loop'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:161:in `loop'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-sftp-2.1.1/lib/net/sftp/session.rb:802:in`loop'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-sftp-2.1.1/lib/net/sftp/operations/download.rb:186:in `wait'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-sftp-2.1.1/lib/net/sftp/session.rb:125:in`download!'
/home/kolmanv/bbfs/lib/testing_server/testing_server.rb:130:in `block in copy_master_index'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-sftp-2.1.1/lib/net/sftp/session.rb:939:in`call'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-sftp-2.1.1/lib/net/sftp/session.rb:939:in `block in do_version'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-sftp-2.1.1/lib/net/sftp/session.rb:939:in`each'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-sftp-2.1.1/lib/net/sftp/session.rb:939:in `do_version'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-sftp-2.1.1/lib/net/sftp/session.rb:909:in`when_channel_polled'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-ssh-2.6.6/lib/net/ssh/connection/channel.rb:311:in `call'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-ssh-2.6.6/lib/net/ssh/connection/channel.rb:311:in`process'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:214:in `block in prepro
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:214:in`each'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:214:in `preprocess'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:197:in`process'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:161:in `block in loop'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:161:in`loop'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-ssh-2.6.6/lib/net/ssh/connection/session.rb:161:in `loop'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-sftp-2.1.1/lib/net/sftp/session.rb:802:in`loop'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-sftp-2.1.1/lib/net/sftp/session.rb:787:in `connect!'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/net-sftp-2.1.1/lib/net/sftp.rb:32:in`start'
/home/kolmanv/bbfs/lib/testing_server/testing_server.rb:129:in `copy_master_index'
/home/kolmanv/bbfs/lib/testing_server/testing_server.rb:92:in`run_testing_server'
bin/testing_server:13:in `block in <main>'
/home/kolmanv/bbfs/lib/run_in_background.rb:400:in`run'
bin/testing_server:13:in `<main>'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/log4r-1.1.10/lib/log4r/outputter/iooutputter.rb:43:in`flush': Disk quo
        from /usr/local/rvm/gems/ruby-1.9.2-p320/gems/log4r-1.1.10/lib/log4r/outputter/iooutputter.rb:43:in `wri
        from /usr/local/rvm/gems/ruby-1.9.2-p320/gems/log4r-1.1.10/lib/log4r/outputter/outputter.rb:110:in`bloc
        from /usr/local/rvm/gems/ruby-1.9.2-p320/gems/log4r-1.1.10/lib/log4r/outputter/outputter.rb:130:in `bloc
        from /usr/local/rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/monitor.rb:201:in`mon_synchronize'
        from /usr/local/rvm/gems/ruby-1.9.2-p320/gems/log4r-1.1.10/lib/log4r/outputter/outputter.rb:130:in `sync
        from /usr/local/rvm/gems/ruby-1.9.2-p320/gems/log4r-1.1.10/lib/log4r/outputter/outputter.rb:110:in`cano
        from (eval):3:in `error'
        from (eval):8:in`block in error'
        from (eval):8:in `each'
        from (eval):8:in`error'
        from /home/kolmanv/bbfs/lib/testing_server/testing_server.rb:120:in `rescue in run_testing_server'
        from /home/kolmanv/bbfs/lib/testing_server/testing_server.rb:60:in`run_testing_server'
        from bin/testing_server:13:in `block in <main>'
        from /home/kolmanv/bbfs/lib/run_in_background.rb:400:in`run'
        from bin/testing_server:13:in `<main>'

**Comment by bbfsdev** [comment] 2013-06-03 04:07
Duplicate of #136 Closing this issue.

**Closed as completed by bbfsdev** 2013-06-03 04:07 UTC
