### ISSUE TITLE
Run in background enters in endless loop in certain scenarios

### ISSUE THREAD

**Issue by genadyp** [bbfsdev/bbfs#142] opened 2013-05-24 16:23 UTC
Branch: Release 1.0.0

Run in background enters in endless loop when:
- issue incorrect background command
- delete command (but background process actually finished)
- start command for already running server (process still running after issue delete command)

**Comment by genadyp** [comment] 2013-08-14 07:18
@kolmanv 
@yarondbb 
@AlexeyNemytov 

Volodia wants to check background option.
May be worth to define this issue as critical?

**Comment by yarondbb** [comment] 2013-08-15 18:32
fixed in brnach: issue-142-background-loop
Root cause was endless while loop in bin<application> when execution finished with no exception and loop counter was not reduced below zero.
I cenceld the endless loop mechanism since we are not using it currently.
Pull request opend for @kolmanv. I will close this issue after merge

**Comment by yarondbb** [comment] 2013-08-15 18:37
related to #220 (the pull request

**Closed as completed** 2013-09-14 16:09 UTC
Labels: Critical
