### ISSUE TITLE
Exception when deleting files during content_server run

### ISSUE THREAD

**Issue by AlexeyNemytov** [bbfsdev/bbfs#170] opened 2013-06-15 18:01 UTC
Delete files from working directory during normal operation causes an error

```[ERROR] [2013-06-15 17:54:56] [content_server:28:Exception happened in content_server server: Errno::ENOENT:No such file or directory - C:/Users/Alexey/.bbfs/test_files/test_dir_4_backup_server_1344584350_6n8y935z/auto_generated_file_4_backup_server_1344584350_v6k9u5nl.txt
Backtrace:
C:/Ruby192/bbfs/lib/file_indexing/index_agent.rb:166:in`lstat'
C:/Ruby192/bbfs/lib/file_indexing/index_agent.rb:166:in `global_path'
C:/Ruby192/bbfs/lib/content_server/queue_indexer.rb:72:in`block in run']

```
```

**Comment by yarondbb** [comment] 2013-06-17 13:16
Root cause is that removed path is still living in the indexing queue
Then, when indexing and trying to get the file status and mtime we get the exception.
This is fixed in branch: release_1_1_0 (rescue block was added to catch this and ingnor the file. The assumption is that later an event of non-existing will be sent using the queue and the file\dir will be removed) 

I think the issue can be closed..

**Closed as completed** 2013-06-22 08:51 UTC
